name: AWS Connection Test

on:
  push:
    branches:
      - main  # O la rama principal de tu repositorio

jobs:
  aws-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-1"  # Cambia a tu región

      - name: Test AWS connection
        run: aws sts get-caller-identity